import type { EbgSettings } from "../models/interfaces";

export type BuilderSettings = Record<string, unknown>;

function joinWhiteLists(entities: string[], prefixes: string[]): string[] {
    const prefixWild = prefixes.map((p) => (p.includes("*") ? p : p + "*"));
    return [...entities, ...prefixWild];
}

export function buildBuilderSettings(s: EbgSettings): BuilderSettings {
    const generateOptionSetProperties = !s.generateEnumProperties || (s.generateEnumProperties && !s.replaceOptionSetPropertiesWithEnum);

    const dlab: Record<string, unknown> = {};

    dlab["addDebuggerNonUserCode"] = s.addDebuggerNonUserCode;
    dlab["addNewFilesToProject"] = s.addNewFilesToProject;
    dlab["addOptionSetMetadataAttribute"] = s.addOptionSetMetadataAttribute;
    dlab["adjustCasingForEnumOptions"] = s.adjustCasingForEnumOptions;
    dlab["attributeBlacklist"] = s.attributeBlacklist;
    dlab["builderSettingsJsonRelativePath"] = s.builderSettingsJsonRelativePath;
    dlab["camelCaseClassNames"] = s.camelCaseClassNames;

    dlab["camelCaseMemberNames"] = s.camelCaseMemberNames;
    dlab["camelCaseNamesDictionaryRelativePath"] = s.camelCaseNamesDictionaryRelativePath;
    dlab["cleanupCrmSvcUtilLocalOptionSets"] = s.cleanupCrmSvcUtilLocalOptionSets;
    dlab["createOneFilePerMessage"] = s.createOneFilePerMessage;
    dlab["createOneFilePerEntity"] = s.createOneFilePerEntity;
    dlab["createOneFilePerOptionSet"] = s.createOneFilePerOptionSet;
    dlab["deleteFilesFromOutputFolders"] = s.deleteFilesFromOutputFolders;

    const lowercasedOverrides: Record<string, string> = {};
    for (const [k, v] of Object.entries(s.entityClassNameOverrides)) {
        lowercasedOverrides[k] = v.toLowerCase();
    }
    if (Object.keys(lowercasedOverrides).length > 0) {
        dlab["entityClassNameOverrides"] = lowercasedOverrides;
    }

    if (!s.createOneFilePerEntity) {
        dlab["entitiesFileName"] = s.entityTypesFolder;
    }

    dlab["generateMessageAttributeNameConsts"] = s.generateMessageAttributeNameConsts;
    if (s.addOptionSetMetadataAttribute) {
        dlab["generateAllOptionSetLabelMetadata"] = s.generateAllOptionSetLabelMetadata;
    }
    dlab["generateAttributeNameConsts"] = s.generateAttributeNameConsts;
    dlab["generateAnonymousTypeConstructor"] = s.generateAnonymousTypeConstructor;
    dlab["generateConstructorsSansLogicalName"] = s.generateConstructorsSansLogicalName;
    dlab["generateEntityRelationships"] = s.generateEntityRelationships;
    dlab["generateOptionSetProperties"] = generateOptionSetProperties;
    dlab["generateOptionSetMetadataAttribute"] = s.generateOptionSetMetadataAttribute;
    dlab["generateTypesAsInternal"] = s.generateTypesAsInternal;
    dlab["groupLocalOptionSetsByEntity"] = s.groupLocalOptionSetsByEntity;
    dlab["groupMessageRequestWithResponse"] = s.groupMessageRequestWithResponse;
    dlab["includeCommandLine"] = s.includeCommandLine;
    dlab["invalidCSharpNamePrefix"] = s.invalidCSharpNamePrefix;
    dlab["localOptionSetFormat"] = s.localOptionSetFormat;
    dlab["makeAllFieldsEditable"] = s.makeAllFieldsEditable;
    dlab["makeReadonlyFieldsEditable"] = s.makeReadonlyFieldsEditable;
    dlab["makeReferenceTypesNullable"] = s.makeReferenceTypesNullable;
    dlab["makeResponseMessagesEditable"] = s.makeResponseMessagesEditable;

    if (!s.createOneFilePerMessage) {
        dlab["messagesFileName"] = s.messageTypesFolder;
    }
    dlab["modelBuilderLogLevel"] = s.modelBuilderLogLevel;
    dlab["obsoleteDeprecated"] = s.obsoleteDeprecated;
    dlab["obsoleteTokens"] = s.obsoleteTokens;

    if (!s.createOneFilePerOptionSet) {
        dlab["optionSetsFileName"] = s.optionSetsTypesFolder;
    }

    if (s.optionSetLanguageCodeOverride !== null) {
        dlab["optionSetLanguageCodeOverride"] = String(s.optionSetLanguageCodeOverride);
    }
    if (Object.keys(s.optionSetNames).length > 0) {
        dlab["optionSetNames"] = s.optionSetNames;
    }
    if (Object.keys(s.optionNameOverrides).length > 0) {
        dlab["optionNameOverrides"] = s.optionNameOverrides;
    }

    dlab["readSerializedMetadata"] = s.readSerializedMetadata;
    dlab["removeRuntimeVersionComment"] = s.removeRuntimeVersionComment;

    dlab["serializeMetadata"] = s.serializeMetadata;
    dlab["suppressAutogeneratedFileHeaderComment"] = s.suppressAutogeneratedFileHeaderComment;
    dlab["tokenCapitalizationOverrides"] = s.tokenCapitalizationOverrides;
    dlab["transliterationRelativePath"] = s.transliterationRelativePath;
    dlab["useLogicalNames"] = s.useLogicalNames;
    dlab["useCrmSvcUtilStateEnumNamingConvention"] = s.useCrmSvcUtilStateEnumNamingConvention;
    dlab["useDisplayNameForBpfName"] = s.useDisplayNameForBpfName;
    dlab["useTfsToCheckoutFiles"] = false;
    dlab["waitForAttachedDebugger"] = s.waitForAttachedDebugger;

    const result: BuilderSettings = {};

    if (s.codeCustomizationService) result["codeCustomizationService"] = s.codeCustomizationService;
    if (s.codeGenerationService) result["codeGenerationService"] = s.codeGenerationService;
    if (s.codeWriterFilterService) result["codeWriterFilterService"] = s.codeWriterFilterService;
    if (s.codeWriterMessageFilterService) result["codeWriterMessageFilterService"] = s.codeWriterMessageFilterService;

    result["dLaB.ModelBuilder"] = dlab;

    result["emitEntityETC"] = s.emitEntityETC;
    result["emitFieldsClasses"] = s.generateAttributeNameConsts;
    result["emitVirtualAttributes"] = s.emitVirtualAttributes;

    const entityNames = joinWhiteLists(s.entitiesWhitelist, s.entityPrefixesWhitelist);
    if (entityNames.length > 0) {
        result["entityNamesFilter"] = entityNames;
    }

    result["entityTypesFolder"] = s.entityTypesFolder.includes(".cs") ? "Entities" : s.entityTypesFolder;
    result["generateActions"] = s.generateMessages;
    result["generateGlobalOptionSets"] = s.generateGlobalOptionSets;

    if (s.generateMessages) {
        const msgNames = joinWhiteLists(s.messagesWhitelist, s.messagePrefixesWhitelist);
        if (msgNames.length > 0) {
            result["messageNamesFilter"] = msgNames;
        }
        const msgFolder = s.messageTypesFolder.includes(".cs") ? "Messages" : s.messageTypesFolder;
        if (msgFolder) result["messagesTypesFolder"] = msgFolder;
    }

    if (s.metadataProviderService) result["metadataProviderService"] = s.metadataProviderService;
    if (s.metadataQueryProviderService) result["metadataQueryProviderService"] = s.metadataQueryProviderService;
    if (s.namespace) result["namespace"] = s.namespace;
    if (s.namingService) result["namingService"] = s.namingService;

    const optSetsFolder = s.optionSetsTypesFolder.includes(".cs") ? "OptionSets" : s.optionSetsTypesFolder;
    if (optSetsFolder) result["optionSetsTypesFolder"] = optSetsFolder;

    if (s.serviceContextName) result["serviceContextName"] = s.serviceContextName;
    result["suppressGeneratedCodeAttribute"] = s.suppressGeneratedCodeAttribute;
    result["suppressINotifyPattern"] = !s.generateINotifyPattern;

    return result;
}
