export const T = "\t";
export const T2 = "\t\t";
export const T3 = "\t\t\t";
export const T4 = "\t\t\t\t";
export const T5 = "\t\t\t\t\t";

export function escapeXmlComment(text: string): string {
    return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function generateSummary(text: string | undefined, indent: string): string {
    if (!text) return "";
    return `${indent}/// <summary>\n${indent}/// ${escapeXmlComment(text)}\n${indent}/// </summary>\n`;
}

export function isObsolete(displayName: string | undefined, obsoleteTokens: string[]): boolean {
    if (!displayName || obsoleteTokens.length === 0) return false;
    for (const token of obsoleteTokens) {
        const regexStr = "^" + token.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\*/g, ".*") + "$";
        if (new RegExp(regexStr, "i").test(displayName)) return true;
    }
    return false;
}

export function extractNamespaceBody(fileContent: string, namespace_: string): string {
    const nsLine = `namespace ${namespace_}`;
    const start = fileContent.indexOf(nsLine);
    if (start === -1) return fileContent;

    const braceStart = fileContent.indexOf("{", start);
    if (braceStart === -1) return fileContent;

    let depth = 0;
    let end = braceStart;
    for (let i = braceStart; i < fileContent.length; i++) {
        if (fileContent[i] === "{") depth++;
        else if (fileContent[i] === "}") {
            depth--;
            if (depth === 0) {
                end = i;
                break;
            }
        }
    }
    return fileContent.slice(braceStart + 1, end).trimEnd();
}

export function codeFileHeader(namespace_: string): string[] {
    return [
        "#nullable enable",
        "#pragma warning disable CS1591",
        "//------------------------------------------------------------------------------",
        "// <auto-generated>",
        "//     This code was generated by a tool.",
        "//",
        "//     Changes to this file may cause incorrect behavior and will be lost if",
        "//     the code is regenerated.",
        "// </auto-generated>",
        "//------------------------------------------------------------------------------",
        "",
        `namespace ${namespace_}`,
        "{",
    ];
}
