export interface EbgSettings {
    namespace: string;
    serviceContextName: string;
    outputRelativeDirectory: string;
    builderSettingsJsonRelativePath: string;
    suppressGeneratedCodeAttribute: boolean;
    removeRuntimeVersionComment: boolean;
    suppressAutogeneratedFileHeaderComment: boolean;
    generateTypesAsInternal: boolean;
    includeCommandLine: boolean;
    filePrefixText: string;
    makeReferenceTypesNullable: boolean;
    useDisplayNameForBpfName: boolean;
    addNewFilesToProject: boolean;
    deleteFilesFromOutputFolders: boolean;
    projectNameForEarlyBoundFiles: string;
    tokenCapitalizationOverrides: string[];
    camelCaseClassNames: boolean;
    camelCaseMemberNames: boolean;
    camelCaseCustomWords: string[];
    camelCaseNamesDictionaryRelativePath: string;

    entityTypesFolder: string;
    createOneFilePerEntity: boolean;
    entitiesWhitelist: string[];
    entitiesToSkip: string[];
    entityPrefixesToSkip: string[];
    entityPrefixesWhitelist: string[];
    entityClassNameOverrides: Record<string, string>;
    entityAttributeSpecifiedNames: Record<string, string[]>;
    attributeBlacklist: string[];
    generateAttributeNameConsts: boolean;
    generateAnonymousTypeConstructor: boolean;
    generateConstructorsSansLogicalName: boolean;
    generateEntityRelationships: boolean;
    generateEnumProperties: boolean;
    replaceOptionSetPropertiesWithEnum: boolean;
    generateINotifyPattern: boolean;
    emitVirtualAttributes: boolean;
    emitEntityETC: boolean;
    makeAllFieldsEditable: boolean;
    makeReadonlyFieldsEditable: boolean;
    useLogicalNames: boolean;
    useEnumForStateCodes: boolean;
    useCrmSvcUtilStateEnumNamingConvention: boolean;
    obsoleteDeprecated: boolean;
    obsoleteTokens: string[];
    propertyEnumMappings: string[];
    addDebuggerNonUserCode: boolean;

    optionSetsTypesFolder: string;
    createOneFilePerOptionSet: boolean;
    generateGlobalOptionSets: boolean;
    generateOptionSetMetadataAttribute: boolean;
    addOptionSetMetadataAttribute: boolean;
    generateAllOptionSetLabelMetadata: boolean;
    adjustCasingForEnumOptions: boolean;
    groupLocalOptionSetsByEntity: boolean;
    cleanupCrmSvcUtilLocalOptionSets: boolean;
    invalidCSharpNamePrefix: string;
    localOptionSetFormat: string;
    optionSetLanguageCodeOverride: number | null;
    optionSetNames: Record<string, string>;
    optionNameOverrides: Record<string, string>;
    transliterationRelativePath: string;

    generateMessages: boolean;
    messageTypesFolder: string;
    createOneFilePerMessage: boolean;
    messagesWhitelist: string[];
    messagesToSkip: string[];
    messagePrefixesWhitelist: string[];
    groupMessageRequestWithResponse: boolean;
    generateMessageAttributeNameConsts: boolean;
    makeResponseMessagesEditable: boolean;

    codeCustomizationService: string;
    codeGenerationService: string;
    codeWriterFilterService: string;
    codeWriterMessageFilterService: string;
    metadataProviderService: string;
    metadataQueryProviderService: string;
    namingService: string;

    modelBuilderLogLevel: string;
    updateBuilderSettingsJson: boolean;
    readSerializedMetadata: boolean;
    serializeMetadata: boolean;
    waitForAttachedDebugger: boolean;
}

export const DEFAULT_SETTINGS: EbgSettings = {
    namespace: "DataverseModel",
    serviceContextName: "DataverseContext",
    outputRelativeDirectory: "",
    builderSettingsJsonRelativePath: "builderSettings.json",
    suppressGeneratedCodeAttribute: true,
    removeRuntimeVersionComment: true,
    suppressAutogeneratedFileHeaderComment: false,
    generateTypesAsInternal: false,
    includeCommandLine: false,
    filePrefixText: "",
    makeReferenceTypesNullable: false,
    useDisplayNameForBpfName: true,
    addNewFilesToProject: true,
    deleteFilesFromOutputFolders: false,
    projectNameForEarlyBoundFiles: "",
    tokenCapitalizationOverrides: [
        "AccessTeam",
        "ActiveState",
        "AssignedTo",
        "BusinessAs",
        "CardUci",
        "DefaultOnCase",
        "EmailAnd",
        "EmailSend",
        "EmailSender",
        "ExchangeRate",
        "FeatureSet",
        "FedEx",
        "ForAn",
        "Geronimo",
        "IsMsTeams",
        "IsPaiEnabled",
        "IsSopIntegration",
        "MsDynCe_",
        "MsDynMkt_",
        "MsDyUsd",
        "O365Admin",
        "OcSkillIdentMlModel",
        "OnHold",
        "OrderId",
        "OwnerOnAssign",
        "ParticipatesIn",
        "PartiesOnEmail",
        "PauseStates",
        "PredictiveAddress",
        "SentOn",
        "SettingsAndSummary",
        "SlaId",
        "SlaKpi",
        "SyncOptIn",
        "Timeout",
        "TradeShow",
        "UserPuid",
        "VoiceMail",
    ],
    camelCaseClassNames: true,
    camelCaseMemberNames: true,
    camelCaseCustomWords: [],
    camelCaseNamesDictionaryRelativePath: "",

    entityTypesFolder: "Entities",
    createOneFilePerEntity: true,
    entitiesWhitelist: ["activityparty", "activitypointer", "businessunit", "contact", "email", "systemuser", "transactioncurrency"],
    entitiesToSkip: [],
    entityPrefixesToSkip: [],
    entityPrefixesWhitelist: [],
    entityClassNameOverrides: {},
    entityAttributeSpecifiedNames: {},
    attributeBlacklist: [],
    generateAttributeNameConsts: true,
    generateAnonymousTypeConstructor: true,
    generateConstructorsSansLogicalName: true,
    generateEntityRelationships: true,
    generateEnumProperties: true,
    replaceOptionSetPropertiesWithEnum: true,
    generateINotifyPattern: false,
    emitVirtualAttributes: true,
    emitEntityETC: false,
    makeAllFieldsEditable: false,
    makeReadonlyFieldsEditable: false,
    useLogicalNames: false,
    useEnumForStateCodes: false,
    useCrmSvcUtilStateEnumNamingConvention: false,
    obsoleteDeprecated: true,
    obsoleteTokens: ["*(Deprecated)*"],
    propertyEnumMappings: [],
    addDebuggerNonUserCode: true,

    optionSetsTypesFolder: "OptionSets",
    createOneFilePerOptionSet: true,
    generateGlobalOptionSets: false,
    generateOptionSetMetadataAttribute: true,
    addOptionSetMetadataAttribute: true,
    generateAllOptionSetLabelMetadata: false,
    adjustCasingForEnumOptions: true,
    groupLocalOptionSetsByEntity: false,
    cleanupCrmSvcUtilLocalOptionSets: false,
    invalidCSharpNamePrefix: "_",
    localOptionSetFormat: "{0}_{1}",
    optionSetLanguageCodeOverride: null,
    optionSetNames: {},
    optionNameOverrides: {
        "1st": "1st",
        "2nd": "2nd",
        "3rd": "3rd",
        "4th": "4th",
        "5th": "5th",
        "6th": "6th",
        "7th": "7th",
        "8th": "8th",
        "9th": "9th",
        "0th": "0th",
        conversationIndex: "ConversationIndex",
        customcorrelation: "CustomCorrelation",
        fedex: "FedEx",
        groupme: "GroupMe",
        linkedin: "LinkedIn",
        nontransient: "NonTransient",
        notset: "NotSet",
        reminderexpired: "ReminderExpired",
        reminderinvalid: "ReminderInvalid",
        reminderset: "ReminderSet",
        smartmatching: "SmartMatching",
        trackingtoken: "TrackingToken",
        xheader: "XHeader",
    },
    transliterationRelativePath: "",

    generateMessages: true,
    messageTypesFolder: "Messages",
    createOneFilePerMessage: true,
    messagesWhitelist: ["analyze"],
    messagesToSkip: ["RetrieveAppSettingList", "RetrieveAppSetting", "SaveAppSetting", "msdyn_GetSIFeatureConfiguration"],
    messagePrefixesWhitelist: [],
    groupMessageRequestWithResponse: true,
    generateMessageAttributeNameConsts: true,
    makeResponseMessagesEditable: true,

    codeCustomizationService: "DLaB.ModelBuilderExtensions.CustomizeCodeDomService,DLaB.ModelBuilderExtensions",
    codeGenerationService: "DLaB.ModelBuilderExtensions.CodeGenerationService,DLaB.ModelBuilderExtensions",
    codeWriterFilterService: "DLaB.ModelBuilderExtensions.CodeWriterFilterService,DLaB.ModelBuilderExtensions",
    codeWriterMessageFilterService: "DLaB.ModelBuilderExtensions.CodeWriterMessageFilterService,DLaB.ModelBuilderExtensions",
    metadataProviderService: "DLaB.ModelBuilderExtensions.MetadataProviderService,DLaB.ModelBuilderExtensions",
    metadataQueryProviderService: "DLaB.ModelBuilderExtensions.MetadataQueryProviderService,DLaB.ModelBuilderExtensions",
    namingService: "DLaB.ModelBuilderExtensions.NamingService,DLaB.ModelBuilderExtensions",

    modelBuilderLogLevel: "2",
    updateBuilderSettingsJson: true,
    readSerializedMetadata: false,
    serializeMetadata: false,
    waitForAttachedDebugger: false,
};
